/** User-visible dashboard strings (avoid scattering literals in components). */
export const DashboardCopy = {
  loading: 'Loading…',
  choreTitlePlaceholder: 'Chore title',
  todoTitlePlaceholder: 'To-do title',
  shoppingEmpty: 'Nothing open — add items from Shopping.',
  urgentShoppingEmpty: 'All clear — no urgent shopping.',
  choresEmpty: 'No chores yet — add one above.',
  todosEmpty: 'No open to-dos — add one above.',
  remindersPlaceholder: 'Calendar reminders — coming next.',
  docsPlaceholder: 'Credentials & notes — coming next.',
  mediaServiceKindLabel: 'Service',
  comradesAddLabel: '+ Add Comrade',
  comradesSectionTitle: '★ Comrades',
  comradeRoleLabel: 'Comrade',
  adminRoleLabel: '★ Admin',
  shoppingKindBadge: 'Shopping',
  nudgeHint: 'nudge',
  addButton: 'Add',
  doneButton: 'Done',
  titleFieldLabel: 'Title',
  assignFieldLabel: 'Assign',
  assignOptionalFieldLabel: 'Assign (opt.)',
  scopeFieldLabel: 'Scope',
  householdAddList: '+ Add list ★',
  personalAddItem: '+ Add item ★',
  urgentViewAll: 'View all →',
  choresTodosAdd: '+ Add ★',
  remindersAdd: '+ Add ★',
  mediaManage: 'Manage ★',
  docsViewAll: 'View all →',
  dashboardLoadError: 'Failed to load dashboard',
  hubFallbackName: 'Hub',
  hubHouseholdSuffix: ' · household',
  personalShoppingSuffix: ' · personal',
  choresTodosWidgetTitle: 'Chores & to-dos',
  assigneeSelectNone: '—',
  workTabChores: 'Chores',
  workTabTodos: 'To-dos',
  urgentBadgeSuffix: ' urgent',
  sidebarNavDashboard: 'Dashboard',
  sidebarNavShopping: 'Shopping',
  sidebarNavLogout: 'Log out',
  sidebarIconDashboard: '★',
  sidebarIconShopping: '☐',
  sidebarIconLogout: '⎋',
  urgentWidgetTitle: '★ Urgent items',
  remindersWidgetTitle: 'Reminders',
  mediaServicesWidgetTitle: 'Media & services',
  docsWidgetTitle: 'Docs',
} as const;
