export const DocsPageCopy = {
  title: 'Docs',
  tabNotes: 'Notes',
  tabPasswords: 'Passwords',
  tabContacts: 'Contacts',
  tabServices: 'Services',
  loading: 'Loading…',
  loadError: 'Could not load',
  notesEmpty: 'No reference notes yet.',
  credentialsEmpty: 'No saved passwords yet.',
  contactsEmpty: 'No contacts yet.',
  noteTitleLabel: 'Title',
  noteBodyLabel: 'Body (markdown)',
  noteTagsLabel: 'Tags (comma-separated)',
  noteAdd: 'Add note',
  noteSave: 'Save',
  noteCancelEdit: 'Cancel',
  noteEdit: 'Edit',
  noteDelete: 'Delete',
  credLabel: 'Label',
  credUsername: 'Username',
  credSecret: 'Secret / password',
  credUrl: 'URL or app',
  credNotes: 'Notes',
  credAdd: 'Add',
  credCopy: 'Copy',
  credDelete: 'Delete',
  contactName: 'Name',
  contactPhones: 'Phones (comma-separated)',
  contactEmails: 'Emails (comma-separated)',
  contactCategory: 'Category',
  contactAddress: 'Address',
  contactNotes: 'Notes',
  contactAdd: 'Add',
  contactDelete: 'Delete',
  servicesEmpty: 'No services configured yet.',
  serviceNameLabel: 'Service name',
  serviceUrlLabel: 'URL',
  serviceCategoryLabel: 'Category',
  serviceDescriptionLabel: 'Description',
  serviceAdd: 'Add service',
  serviceSave: 'Save',
  serviceEdit: 'Edit',
  serviceDelete: 'Delete',
  serviceCancelEdit: 'Cancel',
} as const;
